### DISCUSSION TITLE
Installing Docker in Vanilla OS Orchid

### DISCUSSION THREAD

**Discussion by kbdharun** [Vanilla-OS/handbook#108] [Guides]
_This guide/tutorial has been imported from Discord Forums._

Author: [taukakao](https://github.com/taukakao)

---

It's not possible to install it inside the container, since that would need some major changes. So don't install it with apt.

But you can use podman (which is almost identical to docker) on the host or install docker on the host. 

To use podman:
`host-shell pkexec podman`
or:
`host-shell podman`
for rootless containers (in most cases the better choice) 

If you really want to use docker instead of podman, run:
```
abroot pkg add docker.io
abroot pkg apply
reboot
host-shell pkexec docker
```

**Comment by 0chroma** [comment]
Something I ended up doing today was installing `podman-compose` in a container, that way I can use docker-compose files without needing full blown docker

**Comment by pythoninthegrass** [comment]
Thanks for the hints @kbdharun! Found the [discord thread](https://discord.com/channels/1023243680829681704/1240712792332439653). Combined with another user's [reddit post](https://www.reddit.com/r/vanillaos/comments/1em7ke6/how_to_add_docker_into_my_custom_vanilla_os_image/), I pieced together a [custom image](https://github.com/pythoninthegrass/vanillaos) that works out of the box with docker.

The key block is under `modules` in the [recipe.yml](https://github.com/pythoninthegrass/vanillaos/blob/main/recipe.yml):

```yaml
modules:
  - name: init-setup
    type: shell
    commands:
      - lpkg --unlock
      - apt-get update

  - name: install-docker
    type: shell
    commands:
      - install -m 0755 -d /etc/apt/keyrings
      - curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
      - chmod a+r /etc/apt/keyrings/docker.asc
      - echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian bookworm stable" > /etc/apt/sources.list.d/docker.list
      - cat /etc/apt/sources.list.d/docker.list
      - apt-get update
      - apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
```

Hope that saves future visitors who need docker some time 🤞
